version: '3.5'

services:
  app:
    build:
      context: .
      target: build
    volumes:
      - ./:/go/app
    command: go run server.go
    ports:
      - 1323:1323
    networks:
      - webdev

networks:
  webdev:
    external: true
    name: webdev
